### PR TITLE
fixes for fault and rate

### PR DESCRIPTION
**Pull request by bdecoste**

### CODE REVIEW

**Review by thoraxe — CHANGES_REQUESTED** [review]
image links should not include the images folder reference, but the files should be in the images folder.

this is a weird quirk of how workshopper handles images.

**Comment by bdecoste** [comment]
So I need to remove the "image/"? If I do that my local renderer doesn't see the images.

**Comment by thoraxe** [comment]
@bdecoste yes unfortunately it's an annoyance in the way Workshopper works

**Comment by thoraxe** [comment]
Sorry closed by accident.

**Comment by thoraxe** [comment]
It looks like you got rid of your images completely??

**Comment by bdecoste** [comment]
No, there were no images in this PR. This was just fixes after the merged rate and fault PRs. I just got rid of the images/ paths in the adoc.

**Pull request merged**
